In [10]:
#Lectura del csv y visualización
import pandas as pd

file_path = '03_Experimento_2-spreadsheet(v2).csv'
df = pd.read_csv(file_path)

df

,[all run data],[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step].1,num_cultures.1,...,prob_interaction_VF.838,probability_copy.838,per_information_VF.838,[step].839,num_cultures.839,bigger-region.839,prob_interaction_i.839,prob_interaction_VF.839,probability_copy.839,per_information_VF.839
0,NaN,0,889,0,0.00,0.00000,0.00,6.694444,0,885,...,0.000000,0.000000,4.527778,0,898,0,0.00,0.000000,0.000000,4.194444
1,NaN,1,889,2,0.50,0.02439,0.00,6.611111,1,885,...,0.024390,0.034375,4.611111,1,900,1,0.25,0.024390,0.031250,4.388889
2,NaN,2,882,2,0.25,0.02439,0.10,6.527778,2,879,...,0.024390,0.034375,4.777778,2,896,2,0.25,0.024390,0.060366,4.444444
3,NaN,3,868,2,0.50,0.02439,0.15,6.388889,3,877,...,0.024390,0.103720,4.916667,3,894,2,0.25,0.024390,0.031250,4.555556
4,NaN,4,864,2,0.50,0.02439,0.10,6.333333,4,868,...,0.024390,0.054329,5.083333,4,888,2,0.25,0.024390,0.093750,4.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,NaN,9997,7,895,0.75,0.02439,0.00,0.166667,9997,12,...,0.756098,0.046406,100.000000,9997,1,901,0.75,0.268293,0.042188,100.000000
9998,NaN,9998,7,895,0.75,0.02439,0.00,0.166667,9998,12,...,0.756098,0.046406,100.000000,9998,1,901,0.75,0.268293,0.042188,100.000000
9999,NaN,9999,7,895,0.75,0.02439,0.00,0.166667,9999,12,...,0.756098,0.046406,100.000000,9999,1,901,0.75,0.268293,0.042188,100.000000
10000,NaN,10000,7,895,0.75,0.02439,0.00,0.166667,10000,12,...,0.756098,0.046406,100.000000,10000,1,901,0.75,0.268293,0.042188,100.000000
10001,NaN,10001,7,895,0.75,0.02439,0.00,0.166667,10001,12,...,0.756098,0.046406,100.000000,10001,1,901,0.75,0.268293,0.042188,100.000000

In [11]:
file_path_2 = '03_Experimento_2-spreadsheet(v1).csv'
df_2 = pd.read_csv(file_path_2)

df_2.head(7)

,[run number],1,1.1,1.2,1.3,1.4,1.5,1.6,2,2.1,...,839.4,839.5,839.6,840,840.1,840.2,840.3,840.4,840.5,840.6
0,F,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
1,q,14,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,...,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
2,confidence,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN
3,epsilon,0.1,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,...,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN
4,R,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
5,[reporter],[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step],num_cultures,...,prob_interaction_VF,probability_copy,per_information_VF,[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
6,[final],10001,7,895,0.75,0.02439024390243903,0,0.16666666666666669,10001,12,...,0.7560975609756099,0.04640625,100,10001,1,901,0.75,0.26829268292682934,0.0421875,100

In [12]:
df_variables = df_2.iloc[:5]
df_variables

,[run number],1,1.1,1.2,1.3,1.4,1.5,1.6,2,2.1,...,839.4,839.5,839.6,840,840.1,840.2,840.3,840.4,840.5,840.6
0,F,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
1,q,14,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,...,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
2,confidence,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN
3,epsilon,0.1,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,...,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN
4,R,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_2_clean = df_variables.dropna(axis=1, how='all').T

#Se asigna la fila 1 como el nombre de las columnas y elimina esta primera columna
df_2_clean.columns = df_2_clean.iloc[0]
dataframe_2 = df_2_clean.drop(df_2_clean.index[0])
dataframe_2.reset_index(drop=True, inplace=True)
dataframe_2

[run number]  F   q confidence epsilon     R
0             4  14          0     0.1   0.2
1             4  14          0     0.1  0.25
2             4  14          0     0.1   0.3
3             4  14          0     0.1  0.35
4             4  14          0     0.1   0.4
..           ..  ..        ...     ...   ...
835           4  25       0.45     0.1   0.3
836           4  25       0.45     0.1  0.35
837           4  25       0.45     0.1   0.4
838           4  25       0.45     0.1  0.45
839           4  25       0.45     0.1   0.5

[840 rows x 5 columns]

In [14]:
# Elimina las columnas con valores nulos, ademas de transponer el dataframe
data_frame = df.dropna(axis=1, how='all')

data_frame

,[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step].1,num_cultures.1,bigger-region.1,...,prob_interaction_VF.838,probability_copy.838,per_information_VF.838,[step].839,num_cultures.839,bigger-region.839,prob_interaction_i.839,prob_interaction_VF.839,probability_copy.839,per_information_VF.839
0,0,889,0,0.00,0.00000,0.00,6.694444,0,885,0,...,0.000000,0.000000,4.527778,0,898,0,0.00,0.000000,0.000000,4.194444
1,1,889,2,0.50,0.02439,0.00,6.611111,1,885,2,...,0.024390,0.034375,4.611111,1,900,1,0.25,0.024390,0.031250,4.388889
2,2,882,2,0.25,0.02439,0.10,6.527778,2,879,2,...,0.024390,0.034375,4.777778,2,896,2,0.25,0.024390,0.060366,4.444444
3,3,868,2,0.50,0.02439,0.15,6.388889,3,877,2,...,0.024390,0.103720,4.916667,3,894,2,0.25,0.024390,0.031250,4.555556
4,4,864,2,0.50,0.02439,0.10,6.333333,4,868,2,...,0.024390,0.054329,5.083333,4,888,2,0.25,0.024390,0.093750,4.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,9997,7,895,0.75,0.02439,0.00,0.166667,9997,12,879,...,0.756098,0.046406,100.000000,9997,1,901,0.75,0.268293,0.042188,100.000000
9998,9998,7,895,0.75,0.02439,0.00,0.166667,9998,12,879,...,0.756098,0.046406,100.000000,9998,1,901,0.75,0.268293,0.042188,100.000000
9999,9999,7,895,0.75,0.02439,0.00,0.166667,9999,12,879,...,0.756098,0.046406,100.000000,9999,1,901,0.75,0.268293,0.042188,100.000000
10000,10000,7,895,0.75,0.02439,0.00,0.166667,10000,12,879,...,0.756098,0.046406,100.000000,10000,1,901,0.75,0.268293,0.042188,100.000000
10001,10001,7,895,0.75,0.02439,0.00,0.166667,10001,12,879,...,0.756098,0.046406,100.000000,10001,1,901,0.75,0.268293,0.042188,100.000000

In [15]:

valores = data_frame.values
# Guarda una matriz de n filas por 7 columnas tomando como referencia los valores de la segunda fila que en este caso con los reporteros
valores_matriz = valores.reshape(-1, 7)
column_names = [
    "step","num_cultures", "bigger-region", "prob_interaction_i",
    "prob_interaction_VF", "probability_copy", "per_information_VF"
]


df_reshape = pd.DataFrame(valores_matriz)
df_reshape.columns = column_names

df_reshape

,step,num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
0,0.0,889.0,0.0,0.00,0.000000,0.000000,6.694444
1,0.0,885.0,0.0,0.00,0.000000,0.000000,7.500000
2,0.0,886.0,0.0,0.00,0.000000,0.000000,7.194444
3,0.0,892.0,0.0,0.00,0.000000,0.000000,7.944444
4,0.0,895.0,0.0,0.00,0.000000,0.000000,7.611111
...,...,...,...,...,...,...,...
8401675,10001.0,1.0,901.0,0.75,0.756098,0.059062,100.000000
8401676,10001.0,1.0,901.0,0.75,0.756098,0.119085,100.000000
8401677,10001.0,1.0,901.0,0.75,0.756098,0.050625,100.000000
8401678,10001.0,1.0,901.0,0.75,0.756098,0.046406,100.000000
8401679,10001.0,1.0,901.0,0.75,0.268293,0.042188,100.000000

In [16]:
import numpy as np 
df2_repeated = pd.DataFrame(np.tile(dataframe_2.values, (len(df_reshape) // len(dataframe_2) + 1, 1)), columns=dataframe_2.columns).iloc[:len(df_reshape)]
df2_repeated

[run number]  F   q confidence epsilon     R
0             4  14          0     0.1   0.2
1             4  14          0     0.1  0.25
2             4  14          0     0.1   0.3
3             4  14          0     0.1  0.35
4             4  14          0     0.1   0.4
...          ..  ..        ...     ...   ...
8401675       4  25       0.45     0.1   0.3
8401676       4  25       0.45     0.1  0.35
8401677       4  25       0.45     0.1   0.4
8401678       4  25       0.45     0.1  0.45
8401679       4  25       0.45     0.1   0.5

[8401680 rows x 5 columns]

In [17]:
df_combinado = pd.concat([df2_repeated, df_reshape], axis=1)
df_combinado.to_csv('03_Experimento_2-DataBase_2.csv', index= False)
df_combinado

,F,q,confidence,epsilon,R,step,num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
0,4,14,0,0.1,0.2,0.0,889.0,0.0,0.00,0.000000,0.000000,6.694444
1,4,14,0,0.1,0.25,0.0,885.0,0.0,0.00,0.000000,0.000000,7.500000
2,4,14,0,0.1,0.3,0.0,886.0,0.0,0.00,0.000000,0.000000,7.194444
3,4,14,0,0.1,0.35,0.0,892.0,0.0,0.00,0.000000,0.000000,7.944444
4,4,14,0,0.1,0.4,0.0,895.0,0.0,0.00,0.000000,0.000000,7.611111
...,...,...,...,...,...,...,...,...,...,...,...,...
8401675,4,25,0.45,0.1,0.3,10001.0,1.0,901.0,0.75,0.756098,0.059062,100.000000
8401676,4,25,0.45,0.1,0.35,10001.0,1.0,901.0,0.75,0.756098,0.119085,100.000000
8401677,4,25,0.45,0.1,0.4,10001.0,1.0,901.0,0.75,0.756098,0.050625,100.000000
8401678,4,25,0.45,0.1,0.45,10001.0,1.0,901.0,0.75,0.756098,0.046406,100.000000
8401679,4,25,0.45,0.1,0.5,10001.0,1.0,901.0,0.75,0.268293,0.042188,100.000000