In [1]:
#Lectura del csv y visualizaciÃ³n
import pandas as pd

file_path = '03_Experimento_3-spreadsheet(v2).csv'
df = pd.read_csv(file_path)

df.head(7)

,[all run data],[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step].1,num_cultures.1,...,prob_interaction_VF.838,probability_copy.838,per_information_VF.838,[step].839,num_cultures.839,bigger-region.839,prob_interaction_i.839,prob_interaction_VF.839,probability_copy.839,per_information_VF.839
0,NaN,0,890,0,0.00,0.000000,0.00,7.194444,0,894,...,0.000000,0.000000,4.083333,0,899,0,0.00,0.000000,0.00000,3.750000
1,NaN,1,890,1,0.25,0.555556,0.00,7.055556,1,894,...,0.111111,0.034375,4.555556,1,900,1,0.50,0.333333,0.06250,4.111111
2,NaN,2,886,2,0.25,0.111111,0.05,6.944444,2,892,...,0.333333,0.034375,5.027778,2,898,2,0.25,0.111111,0.03125,4.416667
3,NaN,3,878,2,0.25,0.111111,0.00,6.750000,3,887,...,0.333333,0.022500,5.527778,3,897,2,0.25,0.111111,0.03125,4.888889
4,NaN,4,873,2,0.25,0.111111,0.05,6.638889,4,876,...,0.111111,0.034375,5.777778,4,889,2,0.25,0.111111,0.02500,5.250000
5,NaN,5,855,2,0.50,0.111111,0.15,6.527778,5,873,...,0.333333,0.068750,6.166667,5,885,2,0.25,0.111111,0.06250,5.583333
6,NaN,6,850,2,0.50,0.111111,0.10,6.416667,6,862,...,0.333333,0.068750,6.555556,6,873,3,0.25,0.111111,0.06250,5.861111

In [3]:
file_path_2 = '03_Experimento_3-spreadsheet(v1).csv'
df_2 = pd.read_csv(file_path_2)

df_2.head(7)

,[run number],1,1.1,1.2,1.3,1.4,1.5,1.6,2,2.1,...,839.4,839.5,839.6,840,840.1,840.2,840.3,840.4,840.5,840.6
0,F,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
1,q,14,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,...,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
2,confidence,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN
3,epsilon,0.5,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
4,R,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
5,[reporter],[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step],num_cultures,...,prob_interaction_VF,probability_copy,per_information_VF,[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
6,[final],9001,4,687,0.75,0.1111111111111111,0,0,9001,5,...,0.7777777777777778,0.04640625,100,9001,1,901,0.75,0.7777777777777778,0.0421875,100

In [4]:
df_variables = df_2.iloc[:5]
df_variables

,[run number],1,1.1,1.2,1.3,1.4,1.5,1.6,2,2.1,...,839.4,839.5,839.6,840,840.1,840.2,840.3,840.4,840.5,840.6
0,F,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
1,q,14,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,...,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
2,confidence,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN
3,epsilon,0.5,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
4,R,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_2_clean = df_variables.dropna(axis=1, how='all').T

#Se asigna la fila 1 como el nombre de las columnas y elimina esta primera columna
df_2_clean.columns = df_2_clean.iloc[0]
dataframe_2 = df_2_clean.drop(df_2_clean.index[0])
dataframe_2.reset_index(drop=True, inplace=True)
dataframe_2

[run number]  F   q confidence epsilon     R
0             4  14          0     0.5   0.2
1             4  14          0     0.5  0.25
2             4  14          0     0.5   0.3
3             4  14          0     0.5  0.35
4             4  14          0     0.5   0.4
..           ..  ..        ...     ...   ...
835           4  25       0.45     0.5   0.3
836           4  25       0.45     0.5  0.35
837           4  25       0.45     0.5   0.4
838           4  25       0.45     0.5  0.45
839           4  25       0.45     0.5   0.5

[840 rows x 5 columns]

In [6]:
# Elimina las columnas con valores nulos, ademas de transponer el dataframe
data_frame = df.dropna(axis=1, how='all')

data_frame

,[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step].1,num_cultures.1,bigger-region.1,...,prob_interaction_VF.838,probability_copy.838,per_information_VF.838,[step].839,num_cultures.839,bigger-region.839,prob_interaction_i.839,prob_interaction_VF.839,probability_copy.839,per_information_VF.839
0,0,890,0,0.00,0.000000,0.00,7.194444,0,894,0,...,0.000000,0.000000,4.083333,0,899,0,0.00,0.000000,0.000000,3.750000
1,1,890,1,0.25,0.555556,0.00,7.055556,1,894,1,...,0.111111,0.034375,4.555556,1,900,1,0.50,0.333333,0.062500,4.111111
2,2,886,2,0.25,0.111111,0.05,6.944444,2,892,2,...,0.333333,0.034375,5.027778,2,898,2,0.25,0.111111,0.031250,4.416667
3,3,878,2,0.25,0.111111,0.00,6.750000,3,887,2,...,0.333333,0.022500,5.527778,3,897,2,0.25,0.111111,0.031250,4.888889
4,4,873,2,0.25,0.111111,0.05,6.638889,4,876,3,...,0.111111,0.034375,5.777778,4,889,2,0.25,0.111111,0.025000,5.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8997,8997,4,687,0.75,0.111111,0.15,0.000000,8997,5,577,...,0.777778,0.046406,100.000000,8997,1,901,0.75,0.777778,0.042188,100.000000
8998,8998,4,687,0.75,0.111111,0.15,0.000000,8998,5,577,...,0.777778,0.046406,100.000000,8998,1,901,0.75,0.777778,0.042188,100.000000
8999,8999,4,687,0.75,0.111111,0.15,0.000000,8999,5,577,...,0.777778,0.046406,100.000000,8999,1,901,0.75,0.777778,0.042188,100.000000
9000,9000,4,687,0.75,0.111111,0.15,0.000000,9000,5,577,...,0.777778,0.046406,100.000000,9000,1,901,0.75,0.777778,0.042188,100.000000
9001,9001,4,687,0.75,0.111111,0.00,0.000000,9001,5,577,...,0.777778,0.046406,100.000000,9001,1,901,0.75,0.777778,0.042188,100.000000

In [7]:

valores = data_frame.values
# Guarda una matriz de n filas por 7 columnas tomando como referencia los valores de la segunda fila que en este caso con los reporteros
valores_matriz = valores.reshape(-1, 7)
column_names = [
    "step","num_cultures", "bigger-region", "prob_interaction_i",
    "prob_interaction_VF", "probability_copy", "per_information_VF"
]


df_reshape = pd.DataFrame(valores_matriz)
df_reshape.columns = column_names

df_reshape

,step,num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
0,0.0,890.0,0.0,0.00,0.000000,0.000000,7.194444
1,0.0,894.0,0.0,0.00,0.000000,0.000000,6.972222
2,0.0,890.0,0.0,0.00,0.000000,0.000000,6.861111
3,0.0,888.0,0.0,0.00,0.000000,0.000000,7.500000
4,0.0,891.0,0.0,0.00,0.000000,0.000000,6.555556
...,...,...,...,...,...,...,...
7561675,9001.0,1.0,901.0,0.75,0.777778,0.059062,100.000000
7561676,9001.0,1.0,901.0,0.75,0.777778,0.054844,100.000000
7561677,9001.0,1.0,901.0,0.75,0.555556,0.050625,100.000000
7561678,9001.0,1.0,901.0,0.75,0.777778,0.046406,100.000000
7561679,9001.0,1.0,901.0,0.75,0.777778,0.042188,100.000000

In [8]:
import numpy as np 
df2_repeated = pd.DataFrame(np.tile(dataframe_2.values, (len(df_reshape) // len(dataframe_2) + 1, 1)), columns=dataframe_2.columns).iloc[:len(df_reshape)]

In [9]:
df_combinado = pd.concat([df2_repeated, df_reshape], axis=1)
df_combinado.to_csv('03_Experimento_3-DataBase_2.csv', index= False)
df_combinado

,F,q,confidence,epsilon,R,step,num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
0,4,14,0,0.5,0.2,0.0,890.0,0.0,0.00,0.000000,0.000000,7.194444
1,4,14,0,0.5,0.25,0.0,894.0,0.0,0.00,0.000000,0.000000,6.972222
2,4,14,0,0.5,0.3,0.0,890.0,0.0,0.00,0.000000,0.000000,6.861111
3,4,14,0,0.5,0.35,0.0,888.0,0.0,0.00,0.000000,0.000000,7.500000
4,4,14,0,0.5,0.4,0.0,891.0,0.0,0.00,0.000000,0.000000,6.555556
...,...,...,...,...,...,...,...,...,...,...,...,...
7561675,4,25,0.45,0.5,0.3,9001.0,1.0,901.0,0.75,0.777778,0.059062,100.000000
7561676,4,25,0.45,0.5,0.35,9001.0,1.0,901.0,0.75,0.777778,0.054844,100.000000
7561677,4,25,0.45,0.5,0.4,9001.0,1.0,901.0,0.75,0.555556,0.050625,100.000000
7561678,4,25,0.45,0.5,0.45,9001.0,1.0,901.0,0.75,0.777778,0.046406,100.000000
7561679,4,25,0.45,0.5,0.5,9001.0,1.0,901.0,0.75,0.777778,0.042188,100.000000