In [54]:
#Lectura del csv y visualizaci√≥n
import pandas as pd

file_path = '03_Experimento_1-spreadsheet(v2).csv'
df = pd.read_csv(file_path)

df.head(7)

OSError: [Errno 22] Invalid argument

In [49]:
file_path_2 = '03_Experimento_1-spreadsheet(v1).csv'
df_2 = pd.read_csv(file_path_2)

df_2.head(7)

,[run number],1,1.1,1.2,1.3,1.4,1.5,1.6,2,2.1,...,839.4,839.5,839.6,840,840.1,840.2,840.3,840.4,840.5,840.6
0,F,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
1,q,14,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,...,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
2,confidence,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN
3,epsilon,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01,NaN,...,NaN,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN,NaN
4,R,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
5,[reporter],[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step],num_cultures,...,prob_interaction_VF,probability_copy,per_information_VF,[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
6,[final],9001,10,884,0.75,0.002493765586034913,0,0.19444444444444445,9001,10,...,0.002493765586034913,0.152001246882793,94.88888888888889,9001,60,820,0.25,0.002493765586034913,0.051562500000000004,90.97222222222221

In [50]:
df_variables = df_2.iloc[:5]
df_variables

,[run number],1,1.1,1.2,1.3,1.4,1.5,1.6,2,2.1,...,839.4,839.5,839.6,840,840.1,840.2,840.3,840.4,840.5,840.6
0,F,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
1,q,14,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,...,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
2,confidence,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN
3,epsilon,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01,NaN,...,NaN,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN,NaN
4,R,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df_2_clean = df_variables.dropna(axis=1, how='all').T

#Se asigna la fila 1 como el nombre de las columnas y elimina esta primera columna
df_2_clean.columns = df_2_clean.iloc[0]
dataframe_2 = df_2_clean.drop(df_2_clean.index[0])
dataframe_2.reset_index(drop=True, inplace=True)
dataframe_2

[run number]  F   q confidence epsilon     R
0             4  14          0    0.01   0.2
1             4  14          0    0.01  0.25
2             4  14          0    0.01   0.3
3             4  14          0    0.01  0.35
4             4  14          0    0.01   0.4
..           ..  ..        ...     ...   ...
835           4  25       0.45    0.01   0.3
836           4  25       0.45    0.01  0.35
837           4  25       0.45    0.01   0.4
838           4  25       0.45    0.01  0.45
839           4  25       0.45    0.01   0.5

[840 rows x 5 columns]

In [52]:
# Elimina las columnas con valores nulos, ademas de transponer el dataframe
data_frame = df.dropna(axis=1, how='all')

data_frame

,[step],num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF,[step].1,num_cultures.1,bigger-region.1,...,prob_interaction_VF.838,probability_copy.838,per_information_VF.838,[step].839,num_cultures.839,bigger-region.839,prob_interaction_i.839,prob_interaction_VF.839,probability_copy.839,per_information_VF.839
0,0,891,0,0.00,0.000000,0.00,6.972222,0,885,0,...,0.000000,0.000000,4.194444,0,897,0,0.00,0.000000,0.000000,4.250000
1,1,890,2,0.25,0.002494,0.00,6.833333,1,888,1,...,0.002494,0.034375,4.361111,1,897,2,0.25,0.002494,0.062500,4.444444
2,2,886,2,0.25,0.002494,0.05,6.694444,2,882,2,...,0.002494,0.068750,4.472222,2,898,2,0.25,0.002494,0.056671,4.611111
3,3,880,2,0.50,0.002494,0.05,6.555556,3,877,2,...,0.002494,0.034375,4.583333,3,894,2,0.25,0.002494,0.093750,4.833333
4,4,871,2,0.25,0.002494,0.05,6.472222,4,867,3,...,0.002494,0.034375,4.611111,4,886,2,0.75,0.251870,0.093750,4.944444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8997,8997,10,884,0.75,0.002494,0.00,0.194444,8997,10,892,...,0.002494,0.152001,94.888889,8997,59,820,0.75,0.002494,0.051562,91.000000
8998,8998,10,884,0.75,0.002494,0.00,0.194444,8998,10,892,...,0.002494,0.152001,94.888889,8998,60,820,0.75,0.002494,0.051562,90.916667
8999,8999,10,884,0.75,0.002494,0.00,0.194444,8999,10,892,...,0.002494,0.152001,94.888889,8999,59,820,0.50,0.002494,0.028125,90.944444
9000,9000,10,884,0.75,0.002494,0.00,0.194444,9000,10,892,...,0.002494,0.152001,94.888889,9000,60,820,0.75,0.002494,0.051562,91.000000
9001,9001,10,884,0.75,0.002494,0.00,0.194444,9001,10,892,...,0.002494,0.152001,94.888889,9001,60,820,0.25,0.002494,0.051562,90.972222

In [53]:

valores = data_frame.values
# Guarda una matriz de n filas por 7 columnas tomando como referencia los valores de la segunda fila que en este caso con los reporteros
valores_matriz = valores.reshape(-1, 7)
column_names = [
    "step","num_cultures", "bigger-region", "prob_interaction_i",
    "prob_interaction_VF", "probability_copy", "per_information_VF"
]


df_reshape = pd.DataFrame(valores_matriz)
df_reshape.columns = column_names

df_reshape

MemoryError: Unable to allocate 404. MiB for an array with shape (52931760,) and data type float64

In [45]:
import numpy as np 
df2_repeated = pd.DataFrame(np.tile(dataframe_2.values, (len(df_reshape) // len(dataframe_2) + 1, 1)), columns=dataframe_2.columns).iloc[:len(df_reshape)]

In [47]:
df_combinado = pd.concat([df2_repeated, df_reshape], axis=1)
df_combinado.to_csv('02_Experimento_1-DataBase_2.csv', index= False)
df_combinado

,F,q,confidence,epsilon,R,step,num_cultures,bigger-region,prob_interaction_i,prob_interaction_VF,probability_copy,per_information_VF
0,4,14,0,0.01,0.2,0.0,891.0,0.0,0.00,0.000000,0.000000,6.972222
1,4,14,0,0.01,0.25,0.0,885.0,0.0,0.00,0.000000,0.000000,8.083333
2,4,14,0,0.01,0.3,0.0,887.0,0.0,0.00,0.000000,0.000000,7.861111
3,4,14,0,0.01,0.35,0.0,887.0,0.0,0.00,0.000000,0.000000,6.638889
4,4,14,0,0.01,0.4,0.0,887.0,0.0,0.00,0.000000,0.000000,6.638889
...,...,...,...,...,...,...,...,...,...,...,...,...
7561675,4,25,0.45,0.01,0.3,9001.0,43.0,853.0,0.75,0.002494,0.072187,94.555556
7561676,4,25,0.45,0.01,0.35,9001.0,46.0,845.0,0.75,0.002494,0.054844,93.777778
7561677,4,25,0.45,0.01,0.4,9001.0,41.0,850.0,0.75,0.002494,0.050625,94.333333
7561678,4,25,0.45,0.01,0.45,9001.0,37.0,855.0,0.75,0.002494,0.152001,94.888889
7561679,4,25,0.45,0.01,0.5,9001.0,60.0,820.0,0.25,0.002494,0.051562,90.972222